version: '2.4'

services:
  server1:
    build: First-Server/
    ports:
      - "3031:3030"
    mem_limit: 50000000

  server2:
    build: First-Server/
    ports:
      - "3032:3030"
    mem_limit: 50000000
  
  server3:
    build: First-Server/
    ports:
      - "3033:3030"
    mem_limit: 50000000
