version: '2.4'

services:
  server1:
    image: server
    hostname: server1
    ports:
      - "3031:3030"
    mem_limit: 50000000
    environment:
      - COMPOSE_URLS=server1:server2:server3

  server2:
    image: server
    hostname: server2
    ports:
      - "3032:3030"
    mem_limit: 50000000
    environment:
      - COMPOSE_URLS=server1:server2:server3
  
  server3:
    image: server
    hostname: server3
    ports:
      - "3033:3030"
    mem_limit: 50000000
    environment:
      - COMPOSE_URLS=server1:server2:server3
